---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: |
      nvm install
  - init: |
      npm i -g nx commitizen
      npm i

github:
  prebuilds:
    addComment: true
    branches: true

vscode:
  extensions:
    - 'esbenp.prettier-vscode'
    - 'firsttris.vscode-jest-runner'
    - '42crunch.vscode-openapi'
    - 'redhat.vscode-yaml'
    - 'dbaeumer.vscode-eslint'
    - nrwl.angular-console
    - EditorConfig.EditorConfig
