name: PR Test
on:
  pull_request:
    branches: [main]
env:
  NX_BRANCH: ${{ github.event.pull_request.head.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin main
      - run: npm ci
      - name: Run Affected Tests
        shell: bash
        run: |
          npm run affected:test -- --base=remotes/origin/main
          npm run affected:e2e -- --base=remotes/origin/main
